POST http://localhost:5289/customers
Content-Type: application/json

{
    "Name":"Batman",
    "Company": "wayne enterprises",
    "Age": 36
}

###

GET http://localhost:5289/iamunhappyandwilltelluwhy
